#requires -Version 5.1
param(
    [string]$BackendPort = "8000",
    [string]$FrontendPort = "3000",
    [string]$DeepSeekApiKey = "",
    [string]$DeepSeekModel = "deepseek-v4-flash",
    [string]$PaddleOcrToken = "",
    [switch]$EnableOcr,
    [switch]$UseAsyncJobs,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$RootDir = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$BackendDir = Join-Path $RootDir "backend"
$FrontendDir = Join-Path $RootDir "frontend"
$BackendEnvPath = Join-Path $BackendDir ".env"
$FrontendEnvPath = Join-Path $FrontendDir ".env.local"

function Write-Step {
    param([string]$Message)

    Write-Host ""
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Write-EnvFile {
    param(
        [string]$Path,
        [string]$Content,
        [switch]$Force
    )

    if ((Test-Path -LiteralPath $Path) -and -not $Force) {
        Write-Host "Keep existing: $Path"
        return
    }

    $directory = Split-Path -Parent $Path
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
    Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8
    Write-Host "Wrote: $Path"
}

$ApiBaseUrl = "http://127.0.0.1:$BackendPort/api/v1"
$CorsOrigins = "http://localhost:$FrontendPort,http://127.0.0.1:$FrontendPort"
$OcrProvider = if ($EnableOcr -or -not [string]::IsNullOrWhiteSpace($PaddleOcrToken)) {
    "paddleocr"
}
else {
    "none"
}
$UseAsyncJobsValue = if ($UseAsyncJobs) { "true" } else { "false" }

Write-Step "Create local storage directories"
New-Item -ItemType Directory -Force -Path (Join-Path $BackendDir "storage\materials") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $BackendDir "storage\chroma") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $BackendDir "storage\ocr") | Out-Null

Write-Step "Create backend/.env"
$BackendEnvContent = @"
# LearnFlow backend local development config.
# Generated by scripts/setup-env.ps1.
DATABASE_URL=sqlite:///./studyagent.db
REDIS_URL=redis://127.0.0.1:6379/0

DEEPSEEK_API_KEY=$DeepSeekApiKey
DEEPSEEK_BASE_URL=https://api.deepseek.com
DEEPSEEK_MODEL=$DeepSeekModel

OCR_PROVIDER=$OcrProvider
PADDLE_OCR_TOKEN=$PaddleOcrToken
PADDLE_OCR_JOB_URL=https://paddleocr.aistudio-app.com/api/v2/ocr/jobs
PADDLE_OCR_MODEL=PaddleOCR-VL-1.6
OCR_STORAGE_DIR=./storage/ocr

CORS_ORIGINS=$CorsOrigins
MATERIAL_UPLOAD_DIR=./storage/materials
CHROMA_PERSIST_DIR=./storage/chroma
CHUNK_SIZE=800
CHUNK_OVERLAP=120
RAG_ENRICH_MAX_CHUNKS=12
"@
Write-EnvFile -Path $BackendEnvPath -Content $BackendEnvContent -Force:$Force

Write-Step "Create frontend/.env.local"
$FrontendEnvContent = @"
# LearnFlow frontend local development config.
# Generated by scripts/setup-env.ps1.
NEXT_PUBLIC_API_BASE_URL=$ApiBaseUrl
NEXT_PUBLIC_USE_ASYNC_JOBS=$UseAsyncJobsValue
"@
Write-EnvFile -Path $FrontendEnvPath -Content $FrontendEnvContent -Force:$Force

Write-Step "Done"
Write-Host "Backend env:  $BackendEnvPath"
Write-Host "Frontend env: $FrontendEnvPath"
Write-Host ""
Write-Host "Restart backend and frontend for env changes to take effect."
